### ISSUE TITLE
Escape key should release focus on textarea

### ISSUE THREAD

**Issue by gordon-** [ivangabriele/ShareCode#1]
I am using [Vimperator](http://www.vimperator.org/vimperator) in my browser. It’s a useful extension for using Firefox with Vim bindings.

With this extension, it’s important to maintain focus out of any inputs, to stay in command mode. Some JS applications don’t permit easily to blur a field with the Escape key, so I can’t use my bindings. For that reason, and accessibility in general, no application should prevent that behaviour.

So, ShareCode should not maintain focus in the Textarea if the user tries to lose it, with the Escape key or anything else (especially if we’re in read-only mode).

**Comment by ivangabriele** [comment]
I'l implement that today !

**Comment by ivangabriele** [comment]
Release 1.2.0 includes the blur on escape key pressed :)
